Blog/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from websiteBackbone import views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'posts/', include('manageBlog.urls')),
    path(r'finance/', include('financeAnalysis.urls')),
    path(r'analysis/', include('simpleAnalysis.urls')),
    path(r'register/', views.register, name="register"),
    path(r'accounts/', include("django.contrib.auth.urls")),
    path(r'positions/', include('positions.urls')),
    path(r'', include('websiteBackbone.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

financeAnalysis/urls.py
from django.urls import re_path, path
from django.views.generic import DetailView
from . import views
from .models import StockTicker, StockTickerHistory

app_name = 'financeAnalysis'
urlpatterns = [
    path(r'all/', views.StockTickerListView.as_view(model=StockTicker, template_name="views/allTickers.html"),
         name='stockticker-view'),
    path(r'update/', views.financeAnalysisDetail.update, name='update'),
    path(r'backpopulate-all/', views.financeAnalysisDetail.backpopulate_all, name='backpopulate'),
    path(r'backpopulate/<str:stock_ticker_symbol>/', views.financeAnalysisDetail.backpopulate, name='backpopulate'),
    path(r'repopulate/', views.financeAnalysisDetail.repopulate, name='repopulate'),
    path(r'<str:stock_ticker_symbol>/', views.financeAnalysisDetail.analysis_page, name='ticker_analysis'),
    re_path(r'', views.financeAnalysisDetail.analysis_page, name='analysis_page'),
]

websiteBackbone/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path(r'contact/', views.contact, name='contact'),
    path(r'submission/', views.submission, name='submission'),
    path(r'about/', views.about, name='about'),
    path(r'privacypolicy/', views.privacypolicy, name='privacypolicy'),
    path(r'termsconditions/', views.termsconditions, name='termsconditions'),
    path(r'', views.index, name='index'),
]

websiteBackbone/models.py
# from django.db import models
# from django.contrib.auth.models import User
# from django.db.models.signals import post_save
# from django.dispatch import receiver
#
# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     bio = models.TextField(max_length=500, blank=True)
#     location = models.CharField(max_length=30, blank=True)
#     birth_date = models.DateField(null=True, blank=True)
#
#
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

websiteBackbone/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms


class ContactForm(forms.Form):
    contactName = forms.CharField(label='contactName', max_length=100)
    contactSubject = forms.CharField(label='contactSubject', widget=forms.Textarea)
    contactSenderEmail = forms.EmailField(label='contactSenderEmail')
    cc_myself = forms.BooleanField(label='cc_myself', required=False)
    contactMessage = forms.CharField(label='contactMessage', widget=forms.Textarea, max_length=400)

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",'first_name', 'last_name', )

websiteBackbone/views.py
from django.conf import settings
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.contrib import messages
from django.http import HttpResponse, BadHeaderError, HttpResponseRedirect
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.urls import reverse
from websiteBackbone.forms import CustomUserCreationForm, ContactForm


def update_profile(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST, instance=request.user)
        if user_form.is_valid() and request.user.is_authenticated:
            user_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return render(request, 'registration/user_profile.html')
        else:
            messages.error(request, ('Please login or correct the error below.'))
    else:
        user_form = CustomUserCreationForm(instance=request.user)
    return render(request, 'registration/password_change_form.html',
                  {'user_form': user_form} )


def register(request):
     if request.method == "GET":
         return render(
             request, "registration/register.html",
             {"form": CustomUserCreationForm}
         )
     elif request.method == "POST":
         form = CustomUserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             login(request, user)
             return redirect(reverse('index'))
         messages.error(request, ('Please correct the error below.'))
         return render(
             request, "registration/register.html",
             {"form": CustomUserCreationForm}
         )

def about(request):
    return render(request, './websiteBackbone/about.html')

def index(request):
    return render(request, './websiteBackbone/home.html')

def privacypolicy(request):
    return render(request, './websiteBackbone/privacypolicy.html')

def termsconditions(request):
    return render(request, './websiteBackbone/termsconditions.html')

def submission(request):
    return render(request, './websiteBackbone/submission.html',
                  {'content': ['An email has been sent!',
                               'A representative will follow up within 3-5 business days.']})


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            contactSubject = form.cleaned_data['contactSubject']
            contactMessage = form.cleaned_data['contactMessage']
            contactEmail = form.cleaned_data['contactSenderEmail']
            recipients = ['resources@gmjnow.com']
            cc_myself = form.cleaned_data['cc_myself']
            if cc_myself:
                recipients.append(contactEmail)
            try:
                email = EmailMessage(contactSubject, contactMessage, settings.DEFAULT_FROM_EMAIL, recipients)
                email.send()
            except KeyError:
                return HttpResponse('Please fill in all fields')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect('/submission/')
    return render(request, "websiteBackbone/contact.html", {'form': form})

websiteBackbone/templates/websiteBackbone/about.html
{% extends "websiteBackbone/header.html" %}
{% block content %}
    {%  include "./includes/Intro.html" %}
{%  endblock %}

websiteBackbone/templates/websiteBackbone/contact.html
{% extends "websiteBackbone/header.html" %}

{% block content %}
    <section class="jumbotron mb-4">
        <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
        <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us
            directly for quotes, hiring inquiries, or general questions.
        </p>
        <div class="container row">
            <a href="https://www.linkedin.com/in/georgemjohnson/"> LinkedIn |</a>
                    <a href="mailto:resources@gmjnow.com"> Email Us |</a>
                    <a href="https://github.com/GMJNow/GMJNow"> Github</a>
        </div>
        <div class="row">
            <div class="col-md-9 mb-md-0 mb-5">
                <form action="/contact/" method="post">
                    {% csrf_token %}
                    <div class="container row">
                        <div class="col-md-6">
                            <div class="md-form mb-0">
                                <input type="text" id="id_contactName" name="contactName" class="form-control contact-input"
                                       placeholder="Name" value="{{ current_name }}">
                            </div>
                        </div>
                        <div class="container col-md-6">
                            <div class="md-form mb-0">
                                <input type="text" id="id_contactSenderEmail" name="contactSenderEmail"
                                       placeholder="Email" class="form-control contact-input" value="{{ current_email }}">
                            </div>
                        </div>
                    </div>
                    <div class="container row">
                        <div class="col-md-12">
                            <div class="md-form mb-0">
                                <input type="text" id="id_contactSubject" name="contactSubject" class="form-control contact-input"
                                       placeholder="Subject" value="{{ current_subject }}">
                            </div>
                        </div>
                    </div>
                    <div class="container row">
                        <div class="col-md-12">
                            <div class="md-form">
                        <textarea type="text" id="id_contactMessage" name="contactMessage" rows="2"
                                  placeholder="Enter your message here"
                                  class="form-control md-textarea contact-input" value="{{ current_message }}"></textarea>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0" type="submit">Send</button>
                </form>
                <div class="col-md-3 text-center">
        </div>
            </div>
    </section>


{% endblock %}

websiteBackbone/templates/websiteBackbone/header.html
<!DOCTYPE html>
<html>
<head>
    <title>GMJNOW</title>
    {% load static %}
    <meta property="og:image" content="{% static 'img/GMJNOW.jpg' %}">
    <meta property="og:site_name" content="GMJNOW"/>
    <meta charset="utf-8"/>
    <meta property="og:description"
          content="GMJNOW is a computer and finance technology company specializing in engineering quality top-to-bottom full stack software architecture (design, development, deployments, and maintenance); automating, manufacturing, and supporting cloud-based IT infrastructure; and artificial intelligence driven solutions."/>
    <meta property="og:type" content="finance"/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
{#    <script data-ad-client="ca-pub-2028725223208251" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>#}
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-md fixed-top navbar-light" style="background-color: #044962;">
        <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/navbar_logo_150x85.jpg' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <form class="row text-center" style="width: 75%;" method="post" action="{% url 'financeAnalysis:analysis_page' %}">
                {% csrf_token %}
                <div class="col pr-1">
                    <input class="form-control searchFieldText" type="text" maxlength="7" label="stock_ticker_symbol"
                           onkeyup="this.value = this.value.toUpperCase();" name="stock_ticker_symbol"
                           id="stock_ticker_symbol"
                           placeholder="Enter Stock Symbol (e.g. AAPL, AMD, AMZN)" value="{{ stock_ticker_symbol }}"
                           aria-label="Search">
                </div>
                <div class="col-auto px-0">
                    <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0" type="submit">Search</button>
                </div>
                <div>
                    {% if user.is_authenticated %}
                        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0" type="button"><a href="{% url 'logout' %}">Logout</a></button>
                    {% else %}
                        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0" type="button"><a href="{% url 'login' %}">Login</a></button>
                    {% endif %}
                </div>
            </form>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<div style="margin-top: 55px;">
    {% block content %}
    {% endblock %}
    <hr>
</div>

<footer class="footer bg-dark">
    <div class="container row">
        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0 col col-sm-4 col-md-4 col-lg-4"><a href="{% url 'posts-view' %}">Blog</a></button>
        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0 col col-sm-4 col-md-4 col-lg-4"><a href="https://mailchi.mp/0aec99988c6b/gmjnow-finance">Subscribe</a></button>
        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0 col col-sm-4 col-md-4 col-lg-4"><a href="{% url 'termsconditions' %}">Terms and Conditions</a></button>
        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0 col col-sm-4 col-md-4 col-lg-4"><a href="{% url 'contact' %}">Contact Us</a></button>
        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0 col col-sm-4 col-md-4 col-lg-4"><a href="{% url 'privacypolicy' %}">Privacy Policy</a></button>
        <button class="btn btn-outline-success custom-btn-class my-2 my-sm-0 col col-sm-4 col-md-4 col-lg-4"><a href="{% url 'about' %}">About</a></button>
      </div>
      <div>
        <span class="col col-sm-6 col-md-6 col-lg-6"> GMJNOW LLC © 2020</span>
      </div>

      <br />
      <div class="col">DISCLAIMER: NO INVESTMENT ADVICE. Futures, stocks and options trading involves substantial risk
      of loss. An individual should never invest in the securities of any of the companies' mentioned based
      solely on information contained on our website. These are observations. Individuals should assume that all information provided
      regarding companies is not trustworthy unless verified by their own independent research. GMJNOW LLC and its
      affiliates are not responsible for any decisions made based on information presented on this website.</div>


</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</div>
</body>
</html>

websiteBackbone/templates/websiteBackbone/home.html
{% extends "websiteBackbone/header.html" %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <br/>

        <p>This website brings analyzes over <a href="{% url 'financeAnalysis:stockticker-view' %}">3000 recent stock market listings </a> of a variety of industries including the <a
                href="https://en.wikipedia.org/wiki/List_of_S%26P_500_companies" target="_blank">S&P 500</a> to suggest
            whether a stock is in an optimal purchasing position.
            You can search using the ticker symbols (i.e. Amazon is AMZN, Apple is AAPL, etc.)</p>
    </div>
{% endblock %}

websiteBackbone/templates/websiteBackbone/privacypolicy.html
{% extends "websiteBackbone/header.html" %}
{% block content %}
    {%  include "./includes/privacypolicy_text.html" %}
{%  endblock %}

websiteBackbone/templates/websiteBackbone/submission.html
{% extends "websiteBackbone/header.html" %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
    {%  for c in content %}
        <container>
            <h2>{{c}}</h2>
        </container>
    {%  endfor %}
    </div>
{%  endblock %}

websiteBackbone/templates/websiteBackbone/termsconditions.html
{% extends "websiteBackbone/header.html" %}
{% block content %}
    {%  include "./includes/termsconditions_text.html" %}
{%  endblock %}